subcomponents:
  diamond-rings:
    subcomponents:
      diamond-rings-master:
        config:
          buildId: "4674"
  hello-bedrock:
    config:
      image:
        repository: image.tag
        tag: hello-bedrock-master-5059
